fragment User on User {
  id
  displayName
}

fragment WordleResult on WordleResult {
  id
  createdAt
  user {
    ...User
  }
  guesses
}

query results($weekOf: Date!, $groupId: ID) {
  results(weekOf: $weekOf, groupId: $groupId) {
    ...WordleResult
  }
}

mutation postResults($results: String!) {
  postResults(results: $results) {
    ...WordleResult
  }
}

query canPostResults {
  canPostResults
}

query groups {
  groups {
    id
    name
  }
}

query leaderboard($weekOf: Date!) {
  leaderboard(weekOf: $weekOf) {
    entries {
      user {
        ...User
      }
      score
    }
  }
}

query whoami {
  whoami {
    ...User
  }
}
