fragment WordleResult on WordleResult {
  id
  createdAt
  user {
    id
    displayName
  }
  guesses
}

query results($date: Date, $groupId: ID) {
  results(date: $date, groupId: $groupId) {
    ...WordleResult
  }
}

query groups {
  groups {
    id
    name
  }
}

mutation postResults($results: String!) {
  postResults(results: $results) {
    ...WordleResult
  }
}