fragment Group on Group {
  id
  name
  inviteLink
}

fragment User on User {
  id
  displayName
}

fragment WordleResult on WordleResult {
  id
  createdAt
  user {
    ...User
  }
  guesses
  attemptsUsed
  maxAttempts
  score
}

query results($weekOf: Date!, $groupId: ID) {
  results(weekOf: $weekOf, groupId: $groupId) {
    ...WordleResult
  }
}

mutation postResults($results: String!) {
  postResults(results: $results) {
    ...WordleResult
  }
}

query canPostResults($timezoneOffset: Int!) {
  canPostResults(timezoneOffset: $timezoneOffset)
}

query groups {
  groups {
    ...Group
  }
}

query groupWithInviteCode($inviteCode: String!) {
  groupWithInviteCode(inviteCode: $inviteCode) {
    ...Group
  }
}

query leaderboard($weekOf: Date!, $groupId: ID) {
  leaderboard(weekOf: $weekOf, groupId: $groupId) {
    entries {
      user {
        ...User
      }
      score
    }
  }
}

mutation startGroup($name: String!) {
  startGroup(name: $name) {
    ...Group
  }
}

mutation joinGroup($inviteCode: String!) {
  joinGroup(inviteCode: $inviteCode) {
    ...Group
  }
}

mutation sendLoginEmail($email: String!, $inviteCode: String) {
  sendLoginEmail(email: $email, inviteCode: $inviteCode)
}

mutation updateDisplayName($displayName: String!) {
  updateDisplayName(displayName: $displayName) {
    id 
    displayName
  }
}
