export const BAD_INPUT = "BAD_INPUT"
export const NAME_ALREADY_TAKEN = 'NAME_ALREADY_TAKEN'
export const RESULTS_ALREADY_POSTED = 'RESULTS_ALREADY_POSTED'
export const UNKNOWN = 'UNKNOWN'
export const NOT_AUTHORIZED = 'NOT_AUTHORIZED'
export const SERVER_ERROR = 'SERVER_ERROR'
export const TOKEN_EXPIRED = 'TOKEN_EXPIRED'
export const INVALID_WORDLE = 'INVALID_WORDLE'
