name: CI

on:
  push:
    branches:
      - main

defaults:
  run:
    shell: bash

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v2
      - name: Production build cache
        uses: actions/cache@v2
        id: production-cache
        with:
          path: |
            /tmp/docker-cache
          key: build-cache-${{ github.sha }}
          restore-keys: |
            build-cache

      - name: Install flyctl
        run: curl -L https://fly.io/install.sh | FLYCTL_INSTALL=/usr/local sh

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build production image
        run: |
          docker buildx build \
            --build-arg NODE_ENV=production \
            --cache-from "type=local,src=/tmp/docker-cache" \
            --cache-to "type=local,dest=/tmp/docker-cache,mode=max" \
            --tag wordler:${{ github.sha }} \
            --load \
            .

      - name: Deploy production image
        run: fly deploy --image wordler:${{ github.sha }} --access-token ${{ secrets.FLY_API_TOKEN }}
